[project]
name = "personal-wallet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "google-api-python-client",
    "gspread",
    "openpyxl",
    "pandas",
    "pydantic",
    "python-dotenv",
    "python-multipart",
]

[dependency-groups]
dev = [
    # strumenti comuni
]

local = [
    "uvicorn[standard]==0.51.0",
]

cloudflare = [
    "workers-py",
    "workers-runtime-sdk",
]