storage_service:
  provider: google_sheets
  config:
    spreadsheet_id: 1OpS8W4PkstObGHNGdNmpnATOx-k5pOPJlOeItfH46aw
    range_name: Transactions!B5

# parsing_service:
#   provider: fineco
#   config:
#     placeholder: value